### PR TITLE
Fix compatibility with ActiveAdmin 1.4-pre

### LINKED ISSUE #15: undefined local variable or method `build_sidebar' for #<ActiveAdmin::Views::Pages::Index:0x00007f8ae8961a48> Did you mean?  build_head
Hello. Thank you for making this gem. 
However, in my environment it was impossible to move without trouble. The content of the error was **"undefined local variable or method `build_sidebar 'for # <ActiveAdmin :: Views :: Pages :: Index: 0x00007f8ae8961a48> Did you mean?
Build_head."**

Perhaps written in the "build_page_content" method in the library file.
I changed the **"build_sidebar"** to **"sidebar sidebar_sections_for_action"** and it was confirmed that it works.
 I am not confident, but I'm glad if you can check and fix it.

Thank you.

### PR DESCRIPTION
**Pull request by workgena**
- [x] Update testing environment
- [x] Add Travis CI configuration
- [x] Fix compatibility with ActiveAdmin 1.4 / fixes #15

### CODE REVIEW

File: lib/active_admin_sidebar/activeadmin_views_pages_base.rb [hunk 1]
```diff
@@ -9,6 +9,14 @@ def build_page_content
     end
   end
 
+  def build_sidebar
```
Comment (workgena) [inline lib/active_admin_sidebar/activeadmin_views_pages_base.rb]: this is the "magic" method

because of change here https://github.com/activeadmin/activeadmin/commit/bd34a9ef51003e204074a902f7fe14a53eabd585#diff-1ca3d5d936ee4939e354692f648b27e2R76

**Comment by workgena** [comment]
https://github.com/activeadmin-plugins/active_admin_sidebar/blob/1ee1eff8dfff315d4674dd143436c9cef01f04a9/lib/active_admin_sidebar/activeadmin_views_pages_base.rb#L12-L18

this is the "magic" method

because of change here https://github.com/activeadmin/activeadmin/commit/bd34a9ef51003e204074a902f7fe14a53eabd585#diff-1ca3d5d936ee4939e354692f648b27e2R76
